name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build-linux-amd64
      run: env GOOS=linux GOARCH=amd64 go build -o webbk-linux-amd64

    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: webbk-linux-amd64
        path: ./webbk-linux-amd64
        retention-days: 1
